//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyRate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.cbr.ru/scripts/XML_daily.asp")]
        public string ApiEndpoint {
            get {
                return ((string)(this["ApiEndpoint"]));
            }
            set {
                this["ApiEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>AUD</string>
  <string>AZN</string>
  <string>GBP</string>
  <string>AMD</string>
  <string>BYR</string>
  <string>BGN</string>
  <string>BRL</string>
  <string>HUF</string>
  <string>DKK</string>
  <string>USD</string>
  <string>EUR</string>
  <string>INR</string>
  <string>KZT</string>
  <string>CAD</string>
  <string>KGS</string>
  <string>CNY</string>
  <string>MDL</string>
  <string>NOK</string>
  <string>PLN</string>
  <string>RON</string>
  <string>XDR</string>
  <string>SGD</string>
  <string>TJS</string>
  <string>TRY</string>
  <string>TMT</string>
  <string>UZS</string>
  <string>UAH</string>
  <string>CZK</string>
  <string>SEK</string>
  <string>CHF</string>
  <string>ZAR</string>
  <string>KRW</string>
  <string>JPY</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CurrencyCodes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CurrencyCodes"]));
            }
            set {
                this["CurrencyCodes"] = value;
            }
        }
    }
}
